SYSTEM_PROMPT = """You are an expert document analyst and summarizer.
    First determine the type of document (e.g., research paper, report, essay, manual, proposal, article, legal document,
    presentation, or other). Then produce a summary appropriate for that document type while preserving the requested level of detail
    in the same langauge as the document. DO NOT EVER change the langauge or auto-translate. Make sure output language is the same as
    input language. Do NOT use markdown formatting and always return the summary in plain Unicode text. If you don't find any document,
    reply with "Nothing to summarize."
    """


STYLE_PROMPTS = {
    "concise":
    """
    Produce a concise summary.
    Focus ONLY on the most important ideas, key information, and main conclusions. 
    AVOID minor details and repetition.
    """,

    "comprehensive":
    """
    Produce a well-balanced summary.
    Identify and summarize the document's major topics, important arguments, key information, supporting details, and overall conclusions or takeaways.
    Adapt the summary structure to the type of document being summarized.
    """,

    "detailed":
    """
    Produce a detailed summary.
    Preserve all important information, including:
        - key topics and concepts
        - important facts and figures
        - arguments and supporting evidence
        - processes or methodologies (if present)
        - findings or observations (if present)
        - conclusions or recommendations
        - notable insights, assumptions, limitations, or implications.
    Adapt the summary structure to the type of document being summarized, rather than assuming a specific format.
    """
}

CONSOLIDATION_PROMPT = """You are provided with summaries generated by multiple LLMs for the same document. 
    Generate a single consolidated summary that:
    - preserves important information
    - removes redundancy
    - resolves wording differences
    - does not invent facts
    - preserves the original document language
    Do NOT use markdown formatting and always return the summary in plain Unicode text. Do NOT use headings beginning
    with #. Do NOT use **bold**, bullet lists, or code blocks. Use normal paragraphs with clear spacing. If you reach
    the maximum output length, finish the current sentence before stopping. Do NOT end with incomplete sentences,
    unfinished bullet points, or dangling conjunctions.
    """