services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    image: aggregate-summarizer-backend-latest

    container_name: aggregate-summarizer-backend

    # ports:
    #  - "8000:8000"
    # removed for production, uncomment for development, and vice-versa

    env_file:
      - ./backend/.env

    depends_on:
      - redis
    
    restart: unless-stopped


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    image: aggregate-summarizer-frontend-latest

    container_name: aggregate-summarizer-frontend

    ports:
      - "80:80"
      - "443:443"
    # comment above ports and uncomment the following line for development and vice-versa
    #  - "8080:80"
    
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    # comment above lines during development, and uncomment before pushing in git

    depends_on:
      - backend

    restart: unless-stopped




  redis:
    image: redis:7-alpine

    container_name: aggregate-summarizer-redis

    ports:
      - "6379:6379"
    # this is being exposed, can remove since it can communicate using Docker's internal network, keeping it for now though

    restart: unless-stopped



